#!/usr/bin/env bash

set -euo pipefail

export PS4=$'\n+CMD [\D{%Y-%m-%dT%H:%M:%S%z}] [${BASH_SOURCE##*/}:${LINENO}] '

set -x

repo_root="$HOME/repos"

repo_names=(
  hub
  node-app
  react-app
  vault
)

commit_message="chore: refresh pnpm allow builds"
timestamp="$(date -u +%Y%m%d%H%M%S)"
head_branch_name="chore/refresh-pnpm-allow-builds-${timestamp}"

for repo_name in "${repo_names[@]}"; do
  repo_path="${repo_root}/${repo_name}"

  (
    cd "${repo_path}"

    fnm use

    git switch main
    git pull --all --prune
    git switch --create "${head_branch_name}"

    rm -rf node_modules/
    pnpm config delete --location=project allowBuilds
    pnpm install --no-frozen-lockfile --config.strictDepBuilds=false
    pnpm approve-builds --all

    git add --all
    git commit -asS --message "${commit_message}"
    git push --set-upstream origin "${head_branch_name}"

    gh pr create \
      --base main \
      --head "${head_branch_name}" \
      --title "${commit_message}" \
      --body "Refresh pnpm build approvals against the current locked dependency graph. Remove stale package entries, preserve existing decisions for remaining locked dependencies, and approve newly pending builds. Generated by \`scripts/update/pnpm-allow-builds.sh\`." \
      --web

    git switch main
    git branch --delete --force "${head_branch_name}"
  )
done
