#!/usr/bin/env bash

set -euo pipefail

export PS4=$'\n+CMD [\D{%Y-%m-%dT%H:%M:%S%z}] [${BASH_SOURCE##*/}:${LINENO}] '

set -x

repo_root="$HOME/repos"

repo_names=(
  hub
  node-app
  react-app
  vault
)

commit_message="chore: refresh pnpm allow builds"
timestamp="$(date -u +%Y%m%d%H%M%S)"
head_branch_name="chore/refresh-pnpm-allow-builds-${timestamp}"

for repo_name in "${repo_names[@]}"; do
  repo_path="${repo_root}/${repo_name}"

  (
    cd "${repo_path}"

    # 这里需要先检查是否有未提交的
    # 有未提交的则不执行后续命令

    fnm use

    git switch main
    git pull --all --prune
    git switch --create "${head_branch_name}"

    rm -rf node_modules/
    pnpm config delete --location=project allowBuilds
    pnpm install --no-frozen-lockfile --config.strictDepBuilds=false
    pnpm approve-builds --all

    # 这里需要先检查是否有需要提交的
    # 没有需要提交的则不执行后续命令，切换到之前的分支，删除新创建的分支

    git add --all
    git commit -asS --message "${commit_message}"
    git push --set-upstream origin "${head_branch_name}"

    pr_url="$(gh pr create \
      --base main \
      --head "${head_branch_name}" \
      --title "${commit_message}" \
      --body "Reset pnpm build approvals for the current install environment and approve all discovered pending builds. Generated by \`scripts/update/pnpm-allow-builds.sh\`.")"

    gh pr view "${pr_url}" --web

    git switch main
    git branch --delete --force "${head_branch_name}"
  )
done
