#!/usr/bin/env bash

set -euo pipefail

export PS4=$'\n+CMD [\D{%Y-%m-%dT%H:%M:%S%z}] [${BASH_SOURCE##*/}:${LINENO}] '

set -x

repo_root="$HOME/repos"

repo_names=(
  hub
  node-app
  react-app
  vault
)

timestamp="$(date -u +%Y%m%d%H%M%S)"

base_branch_name="main"
head_branch_name="chore/refresh-pnpm-allow-builds-${timestamp}"
commit_message="chore: refresh pnpm allow builds"

for repo_name in "${repo_names[@]}"; do
  repo_path="${repo_root}/${repo_name}"

  (
    cd "${repo_path}"

    if [[ -n "$(git status --porcelain)" ]]; then
      echo "Skip ${repo_name}: the working tree has uncommitted changes."
      exit 0
    fi

    previous_branch_name="$(git branch --show-current)"

    if [[ -z "${previous_branch_name}" ]]; then
      echo "Skip ${repo_name}: HEAD is detached."
      exit 0
    fi

    fnm use

    git switch "${base_branch_name}"
    git pull --all --prune
    git switch --create "${head_branch_name}"

    rm -rf node_modules/
    pnpm config delete --location=project allowBuilds
    pnpm install --no-frozen-lockfile --config.strictDepBuilds=false
    pnpm approve-builds --all

    if [[ -z "$(git status --porcelain)" ]]; then
      echo "Skip ${repo_name}: pnpm build approvals are already up to date."
      git switch "${previous_branch_name}"
      git branch --delete --force "${head_branch_name}"
      exit 0
    fi

    git add --all
    git commit -asS --message "${commit_message}"
    git push --set-upstream origin "${head_branch_name}"

    pr_url="$(gh pr create \
      --base "${base_branch_name}" \
      --head "${head_branch_name}" \
      --title "${commit_message}" \
      --body "Reset pnpm build approvals for the current install environment and approve all discovered pending builds. Generated by \`scripts/update/pnpm-allow-builds.sh\`.")"

    gh pr view "${pr_url}" --web

    git switch "${previous_branch_name}"
    git branch --delete --force "${head_branch_name}"
  )
done
