name: CI

on:
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install Dependencies
        run: npm ci

      # - name: Lint
      #   run: npm run lint
      # Linters

      - name: lint:package-json
        run: npm run lint:package-json

      - name: lint:format
        run: npm run lint:format

      # - name: lint:types
      #   run: npm run lint:types

      # - name: lint:js
      #   run: npm run lint:js

      - name: lint:css
        run: npm run lint:css

      - name: lint:html
        run: npm run lint:html

      - name: lint:md
        run: npm run lint:md

      - name: lint:text
        run: npm run lint:text

      - name: lint:spell
        run: npm run lint:spell
