name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up pnpm
        uses: pnpm/action-setup@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      # - name: Lint
      #   run: pnpm run lint
      # Linters

      - name: format:oxfmt:check
        run: pnpm run format:oxfmt:check

      # - name: typecheck
      #   run: pnpm run typecheck

      # - name: lint:oxlint
      #   run: pnpm run lint:oxlint

      - name: lint:styles
        run: pnpm run lint:styles

      - name: lint:html
        run: pnpm run lint:html

      - name: lint:markdown
        run: pnpm run lint:markdown

      - name: lint:autocorrect
        run: pnpm run lint:autocorrect

      - name: lint:spellcheck
        run: pnpm run lint:spellcheck
