name: Pull Requests Auto-Update
on:
  workflow_call:
    secrets:
      APP_ID:
        required: true
      APP_PRIVATE_KEY:
        required: true
  push:

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a Token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      # cSpell:disable-next-line
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: '${{ steps.generate-token.outputs.token }}'
