name: Pull Requests Auto-Merge
on:
  workflow_call:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      # https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request
      - name: Auto-Merge Dependabot Pull Requests
        if: >
          github.actor == env.DEPENDABOT_USERNAME ||
          github.event.pull_request.user.login == env.DEPENDABOT_USERNAME
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          DEPENDABOT_USERNAME: dependabot[bot]
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
